// tools/fetch-fonts.mjs
// Mirrors the exact font faces the site uses from Google Fonts into fonts/,
// then writes a single fonts.css that points at the local copies.
//
// Only the faces actually referenced by player.jsx are fetched, and only the
// latin + latin-ext subsets. Re-run with `npm run fonts` if the theme fonts change.

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

// Modern UA so Google serves woff2.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

// Weight/style pairs below are the ones player.jsx actually renders:
//   Cormorant Garamond  400 normal (track index), 400 italic (album), 500 italic (title)
//   Bodoni Moda         400 normal (track index), 400 italic (album), 700 normal (title)
//   DM Serif Display    400 normal (title + index), 400 italic (album)
//   Inter Tight         400 normal (body)
//   JetBrains Mono      400 normal (meta), 700 normal (repeat-one badge)
const QUERY = [
  'family=Cormorant+Garamond:ital,wght@0,400;1,400;1,500',
  'family=Bodoni+Moda:ital,opsz,wght@0,6..96,400;0,6..96,700;1,6..96,400',
  'family=DM+Serif+Display:ital@0;1',
  'family=Inter+Tight:wght@400',
  'family=JetBrains+Mono:wght@400;700',
  'display=swap'
].join('&');

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const kebab = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

async function main() {
  const cssUrl = `https://fonts.googleapis.com/css2?${QUERY}`;
  const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status} ${res.statusText}`);
  const css = await res.text();

  // Each block is preceded by a `/* subset */` comment.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error('No @font-face blocks parsed from the Google Fonts response.');

  const out = [
    '/* fonts.css',
    '   Self-hosted web fonts for AudiOptix.',
    '   Generated by tools/fetch-fonts.mjs. Do not hand-edit; re-run `npm run fonts`.',
    '   Source: Google Fonts, served locally so the site makes no third-party font requests. */',
    ''
  ];
  let kept = 0, skipped = 0;

  for (const [, subset, block] of blocks) {
    if (!KEEP_SUBSETS.has(subset)) { skipped++; continue; }

    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const style  = /font-style:\s*([\w]+)/.exec(block)?.[1] ?? 'normal';
    const weight = /font-weight:\s*([\d\s]+);/.exec(block)?.[1].trim().replace(/\s+/g, '-');
    const src    = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    const range  = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    if (!family || !src) throw new Error(`Could not parse a @font-face block:\n${block}`);

    const fam  = kebab(family);
    // <family-kebab>-<weight>-<style>-<subset>.woff2 — the subset suffix is required
    // because latin and latin-ext are separate files for the same weight/style.
    const name = `${fam}-${weight}-${style}-${subset}.woff2`;
    const rel  = `fonts/${fam}/${name}`;
    const href = `${fam}/${name}`;   // fonts.css lives inside fonts/, so its url()s are relative to that folder
    const abs  = join(ROOT, rel);

    const font = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!font.ok) throw new Error(`Font download failed for ${rel}: ${font.status}`);
    await mkdir(dirname(abs), { recursive: true });
    await writeFile(abs, Buffer.from(await font.arrayBuffer()));
    kept++;

    out.push('@font-face {');
    out.push(`  font-family: '${family}';`);
    out.push(`  font-style: ${style};`);
    out.push(`  font-weight: ${weight.replace(/-/g, ' ')};`);
    out.push('  font-display: swap;');
    out.push(`  src: url('${href}') format('woff2');`);
    if (range) out.push(`  unicode-range: ${range};`);
    out.push('}');
    out.push('');
  }

  await writeFile(join(ROOT, 'fonts', 'fonts.css'), out.join('\n'), 'utf8');
  console.log(`Wrote fonts/fonts.css with ${kept} faces (skipped ${skipped} non-latin subsets).`);
}

main().catch((err) => { console.error(err); process.exit(1); });
