// tools/make-sitemap.mjs
// Generates sitemap.xml by scanning the deploy root for pages, so it cannot
// drift out of date the way a hand-maintained list does. Runs as part of
// `npm run build`.
//
// SITE_URL carries the base path: this deploys as a GitHub Pages *project*
// site, so every URL must sit under /audioptix/, not at the origin root.

import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const SITE_URL = 'https://kiarashfa.github.io/audioptix/';

// Error pages are served by the host on failure; they are not content.
const EXCLUDE = new Set(['404.html']);

const entries = (await readdir(ROOT, { withFileTypes: true }))
  .filter((e) => e.isFile() && e.name.endsWith('.html') && !EXCLUDE.has(e.name))
  .map((e) => e.name)
  .sort();

if (!entries.length) {
  console.error('No pages found; refusing to write an empty sitemap.');
  process.exit(1);
}

const lastmod = new Date().toISOString().slice(0, 10);

const urls = entries.map((name) => {
  // index.html is the directory itself, not a file visitors ever link to.
  const loc = name === 'index.html' ? SITE_URL : SITE_URL + name;
  const priority = name === 'index.html' ? '1.0' : '0.5';
  return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n` +
         `    <changefreq>monthly</changefreq>\n    <priority>${priority}</priority>\n  </url>`;
});

const xml = `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by tools/make-sitemap.mjs. Do not hand-edit. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;

await writeFile(join(ROOT, 'sitemap.xml'), xml, 'utf8');
console.log(`Wrote sitemap.xml with ${entries.length} URL(s): ${entries.join(', ')}`);
